<a href="https://colab.research.google.com/github/sunspai1/ML_Code_Practise/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
SEED = 1234

In [3]:
# Set see for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

In [4]:
# Basics
# Creating a rndom tensor
x =  torch.randn(2,3)

In [6]:
type(x)

torch.Tensor

In [7]:
x.shape

torch.Size([2, 3])

In [8]:
x

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])

In [9]:
#Zeros and Ones Tensor
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
y = torch.ones(2,3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
# List to Tensor
x = torch.Tensor([[1,2,3],[2,4,5]])

In [12]:
print(x)

tensor([[1., 2., 3.],
        [2., 4., 5.]])


In [13]:
x.shape

torch.Size([2, 3])

In [14]:
x = torch.Tensor(np.random.rand(2,3))

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
x

tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])

In [18]:
z = np.random.rand(2,3)

In [19]:
z

array([[0.27646426, 0.80187218, 0.95813935],
       [0.87593263, 0.35781727, 0.50099513]])

In [20]:
# Change the tensor type
x = torch.Tensor(3,4)

In [21]:
x.type()

'torch.FloatTensor'

In [22]:
x.long()

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

## Operations in Tensors

In [23]:
#Addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x+y

In [24]:
z.shape

torch.Size([2, 3])

In [26]:
z.long()

tensor([[0, 0, 0],
        [3, 0, 0]])

In [27]:
# Dot Product

x = torch.randn(2,3)
y = torch.randn(3,2)


In [28]:
z = torch.mm(x,y)

In [30]:
z.shape

torch.Size([2, 2])

In [31]:
z

tensor([[ 1.0796, -0.0759],
        [ 1.2746, -0.5134]])

In [32]:
# Transpose
x = torch.randn(2,3)
x.shape

torch.Size([2, 3])

In [33]:
y  = torch.t(x)

In [34]:
y.shape

torch.Size([3, 2])

In [38]:
#Reshape
x = torch.randn(2,3)
z = x.view(3,2)

In [36]:
z

tensor([[ 0.4501,  0.2709],
        [-0.8087, -0.0217],
        [-1.0413,  0.0702]])

In [39]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])

In [41]:
x.shape

torch.Size([2, 3, 4])

In [44]:
a = x.view(x.size(1),-1)

In [46]:
a

tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

In [48]:
b = x.transpose(0,1).contiguous()

In [49]:
b.shape

torch.Size([3, 2, 4])

In [50]:
b

tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

In [51]:
c = b.view(b.size(0),-1)

In [52]:
c.shape

torch.Size([3, 8])

In [53]:
c

tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])

In [54]:
# Dimensional operations
x = torch.randn(2,3)
y = torch.sum(x,dim=0)

In [55]:
z = torch.sum(x, dim=1)

In [56]:
y

tensor([-0.3071, -1.7100,  0.0452])

In [57]:
z

tensor([ 1.4806, -3.4525])

In [58]:
x = torch.randn(3,4)

In [59]:
x

tensor([[ 0.6486,  1.7653,  1.0812,  1.2436],
        [ 0.8971, -0.0784,  0.5548, -0.0845],
        [ 0.5903, -1.0032, -1.7873,  0.0538]])

In [67]:
x[1,1]

tensor(-0.0784)

In [68]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print(f"Values: \n{x}")

Values: 
tensor([[ 0.8246, -0.5723, -0.4876],
        [ 0.1944, -1.0481, -0.0741]])


In [69]:
col_indices = torch.LongTensor([0,2])

In [70]:
col_indices

tensor([0, 2])

In [71]:
chosen  = torch.index_select(x, dim=1, index=col_indices)

In [72]:
chosen

tensor([[ 0.8246, -0.4876],
        [ 0.1944, -0.0741]])

In [73]:
row_indices = torch.LongTensor([0, 1])
col_indices = torch.LongTensor([0, 2])

In [78]:
chosen = x[row_indices, col_indices]

In [79]:
chosen

tensor([ 0.8246, -0.0741])

In [80]:
x = torch.randn(2, 3)
print (x)
print (x.shape)

tensor([[-0.3449, -1.5447,  0.0685],
        [-1.5104, -1.1706,  0.2259]])
torch.Size([2, 3])


In [81]:
y = torch.cat([x,x],dim=0)
print(y)

tensor([[-0.3449, -1.5447,  0.0685],
        [-1.5104, -1.1706,  0.2259],
        [-0.3449, -1.5447,  0.0685],
        [-1.5104, -1.1706,  0.2259]])


In [82]:
y.shape

torch.Size([4, 3])

In [83]:
# Stacking
z = torch.stack([x, x], dim=0) # stack on new dimension
print (z)
print (z.shape)

tensor([[[-0.3449, -1.5447,  0.0685],
         [-1.5104, -1.1706,  0.2259]],

        [[-0.3449, -1.5447,  0.0685],
         [-1.5104, -1.1706,  0.2259]]])
torch.Size([2, 2, 3])


In [85]:
x  = torch.randn(3,4, requires_grad=True)

In [86]:
x

tensor([[ 1.4696, -1.3284,  1.9946, -0.8209],
        [ 1.0061, -1.0664, -0.4572,  0.0901],
        [ 0.4018, -1.1542,  0.1192, -0.7348]], requires_grad=True)

In [87]:
y = 3*x +2

In [89]:
y

tensor([[ 6.4087, -1.9852,  7.9838, -0.4627],
        [ 5.0184, -1.1993,  0.6283,  2.2702],
        [ 3.2054, -1.4625,  2.3577, -0.2043]], grad_fn=<AddBackward0>)

In [88]:
z = y.mean()

In [90]:
z

tensor(1.8798, grad_fn=<MeanBackward0>)

In [91]:
z.backward()

In [92]:
x.grad

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [2]:
import torch
# Is CUDA available?
print (torch.cuda.is_available())

True


In [3]:

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cuda
